"""Constants for the Off-delay integration tests."""

from custom_components.offdelay.const import (
    CONF_CLIMATE_DAY_START_HOUR,
    CONF_CLIMATE_DELTA_TOLERANCE,
    CONF_CLIMATE_NIGHT_START_HOUR,
    CONF_CLIMATES,
    CONF_GUEST_TURN_OFF_DELAY,
    CONF_GUEST_TURN_ON_DELAY,
    CONF_OCCUPANCY_SENSORS,
    CONF_SUMMER_MIN_TEMP,
    CONF_WINTER_MAX_TEMP,
)

MOCK_CONFIG = {
    CONF_WINTER_MAX_TEMP: 15.0,
    CONF_SUMMER_MIN_TEMP: 20.0,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
}

MOCK_CONFIG_WITH_CLIMATE = {
    CONF_WINTER_MAX_TEMP: 15.0,
    CONF_SUMMER_MIN_TEMP: 20.0,
    CONF_CLIMATES: ["climate.living_room", "climate.bedroom"],
    CONF_CLIMATE_DELTA_TOLERANCE: 0.5,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
}

MOCK_CONFIG_WITH_OCCUPANCY = {
    CONF_WINTER_MAX_TEMP: 15.0,
    CONF_SUMMER_MIN_TEMP: 20.0,
    CONF_CLIMATE_DAY_START_HOUR: 8,
    CONF_CLIMATE_NIGHT_START_HOUR: 17,
    CONF_OCCUPANCY_SENSORS: ["binary_sensor.motion_living_room"],
    CONF_GUEST_TURN_ON_DELAY: 5,
    CONF_GUEST_TURN_OFF_DELAY: 15,
}
