name: ðŸž Bug Report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: >
        This issue form is for reporting bugs only!


        If you have a feature or enhancement request, please use the
        [feature request][fr] template.


        [fr]: /offdelay/offdelay-integration/issues/new?template=feature_request.yml
  - type: checkboxes
    attributes:
      label: Requirements
      options:
        - label: >
            I have updated Offdelay to the latest available version.
          required: true
        - label: >
            I did a search to see if there is a similar issue or if a pull
            request is open.
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Offdelay has the issue?
      placeholder: v
      # yamllint disable rule:line-length
      description: >
        Can be found in: [Settings â‡’ Integrations â‡’ Offdelay](https://my.home-assistant.io/redirect/integration/?domain=offdelay).


        [![Open your Home Assistant instance and show the Offdelay integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=offdelay)
      # yamllint enable rule:line-length
  - type: input
    attributes:
      label: What was the last working version of Offdelay?
      placeholder: v
      description: >
        If known, otherwise leave blank.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information
      # yamllint disable rule:line-length
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        Offdelay provides the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data for
        the configuration you are having issues with, and <ins>drag-and-drop
        that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues
        faster.


        Please note: GSP locations are randomized by offsetting the latitude and
        longitude of each location by a random amount, but the same random
        amount is used for every point. This helps keep your location data
        slightly more anonymized, but someone could still use this information
        to obtain insight into your personal offdelays. Please consider this
        before submitting your diagnostic information.
      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.